service: aws-ratting-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  - serverless-offline
  - serverless-lift
  - serverless-iam-roles-per-function
	
resources:
  Resources:
    rateTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: rateTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    rateMediaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: rateMediaTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

constructs:
  rate-calculator-queue:
    type: queue
    worker:
      handler: src/functions/rateMediaCalculator.handler
      environment:
        RATE_MEDIA_TABLE_NAME: rateMediaTable
      iamRoleStatements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
          Resource:
            - !GetAtt rateMediaTable.Arn

functions:
  rateProduct:
    handler: src/functions/rateProduct.handler
    environment:
      QUEUE_URL: ${construct:rate-calculator-queue.queueUrl}
      RATE_TABLE_NAME: rateTable
    events:
      - httpApi:
          path: /rate
          method: post
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
        Resource:
          - !GetAtt rateTable.Arn
  getRateProductMedia:
    handler: src/functions/getRateProductMedia.handler
    environment:
      RATE_MEDIA_TABLE_NAME: rateMediaTable
    events:
      - httpApi:
          path: /rate
          method: get
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
        Resource:
          - !GetAtt rateMediaTable.Arn
